repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: '898691a'
    hooks:
    -   id: autopep8

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen